services:
  kompas:
    build: './app'
    hostname: kompas
    container_name: kompas
    deploy:
      resources:
        limits:
          cpus: "16.0"
    networks:
      - kompas-net
    ports:
      - '7100:8050'
    volumes:
      - './app:/app'
  kompas-db:
    build: './database'
    hostname: kompas-db
    container_name: kompas-db
    networks:
      - kompas-net
    ports:
      - '3306:3306'
    volumes:
      - kompas-db:/var/lib/mysql
  kompas-cache:
    build: './cache'
    hostname: kompas-cache
    container_name: kompas-cache
    networks:
      - kompas-net
    volumes:
      - kompas-cache:/data
  kompas-data-cache:
    build: './cache'
    hostname: kompas-data-cache
    container_name: kompas-data-cache
    networks:
      - kompas-net
    volumes:
      - kompas-data-cache:/data
networks:
  kompas-net:
    driver: bridge

volumes:
  kompas-cache:
    driver: local
  kompas-data-cache:
    driver: local
  kompas-db:
    driver: local