services:
  kompas:
    build: './new'
    hostname: kompas
    container_name: kompas
    networks:
      - kompas-net
    ports:
      - '7100:8050'
    volumes:
      - './new:/app'
  kompas-db:
    build: './database'
    hostname: kompas-db
    container_name: kompas-db
    networks:
      - kompas-net
    ports:
      - '3306:3306'
    volumes:
      - './database/data:/var/lib/mysql'
networks:
  kompas-net:
    driver: bridge