services:
  kompas:
    build: './app'
    hostname: kompas
    container_name: kompas
    cpuset: "0,1,2,3"
    depends_on:
      - kompas-db
      - kompas-cache
      - kompas-data-cache
    deploy:
      resources:
        limits:
          cpus: "4.0"
    networks:
      - kompas-net
    ports:
      - '7100:8050'
    volumes:
      - './app:/app'
      - './app/.env.prod:/app/.env'
  kompas-data-cache:
    build: './cache'
    hostname: kompas-data-cache
    container_name: kompas-data-cache
    networks:
      - kompas-net
    volumes:
      - kompas-data-cache:/data
  kompas-db:
    cpuset: "6,7"
    deploy:
      resources:
        limits:
          cpus: "2.0"
    build:
      context: './database'
      dockerfile: 'Dockerfile.prod'
    hostname: kompas-db
    container_name: kompas-db
    networks:
      - kompas-net
    volumes:
      - kompas-db:/var/lib/mysql
      - './database/backups/:/backups/'
  kompas-cache:
    cpuset: "4,5"
    deploy:
      resources:
        limits:
          cpus: "2.0"
    build: './cache'
    hostname: kompas-cache
    container_name: kompas-cache
    networks:
      - kompas-net
    volumes:
      - kompas-cache:/data
  kompas-portainer:
    image: portainer/portainer-ce:latest
    container_name: kompas-portainer
    hostname: kompas-portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kompas-portainer:/data
    security_opt:
      - no-new-privileges:true
networks:
  kompas-net:
    driver: bridge

volumes:
  kompas-cache:
    driver: local
  kompas-db:
    driver: local
  kompas-data-cache:
    driver: local
  kompas-portainer:
    driver: local