CREATE USER IF NOT EXISTS 'kompas'@'%' IDENTIFIED BY '3x@mplePassword';
CREATE DATABASE kompas;
GRANT ALL PRIVILEGES ON kompas.* TO 'kompas'@'%' IDENTIFIED BY '3x@mplePassword';
USE kompas;
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    is_active BOOLEAN NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE datasheets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    path VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);



CREATE TABLE magiclinks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    link VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    cancelled_at DATETIME
);


DROP TRIGGER IF EXISTS set_default_cancelled_at;

DELIMITER //

CREATE TRIGGER set_default_cancelled_at
BEFORE INSERT ON magiclinks
FOR EACH ROW
BEGIN
    IF NEW.cancelled_at IS NULL THEN
        SET NEW.cancelled_at = TIMESTAMPADD(HOUR, 48, NOW());
    END IF;
END;
//
DELIMITER ;