CREATE USER IF NOT EXISTS 'kompas'@'%' IDENTIFIED BY '3x@mplePassword';
CREATE DATABASE kompas;
GRANT ALL PRIVILEGES ON kompas.* TO 'kompas'@'%' IDENTIFIED BY '3x@mplePassword';
USE kompas;
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);